// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: audit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRequest) Reset() {
	*x = ItemRequest{}
	mi := &file_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRequest) ProtoMessage() {}

func (x *ItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRequest.ProtoReflect.Descriptor instead.
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{0}
}

func (x *ItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BudgetResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Category       string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`                                     // e.g., "Groceries", "Entertainment"
	Suggestion     string                 `protobuf:"bytes,2,opt,name=suggestion,proto3" json:"suggestion,omitempty"`                                 // e.g., "Approved", "Over Budget!"
	RemainingLimit float32                `protobuf:"fixed32,3,opt,name=remaining_limit,json=remainingLimit,proto3" json:"remaining_limit,omitempty"` // How much left in this category
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BudgetResponse) Reset() {
	*x = BudgetResponse{}
	mi := &file_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetResponse) ProtoMessage() {}

func (x *BudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetResponse.ProtoReflect.Descriptor instead.
func (*BudgetResponse) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{1}
}

func (x *BudgetResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BudgetResponse) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *BudgetResponse) GetRemainingLimit() float32 {
	if x != nil {
		return x.RemainingLimit
	}
	return 0
}

var File_audit_proto protoreflect.FileDescriptor

const file_audit_proto_rawDesc = "" +
	"\n" +
	"\vaudit.proto\x12\x05proto\"7\n" +
	"\vItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\"u\n" +
	"\x0eBudgetResponse\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x02 \x01(\tR\n" +
	"suggestion\x12'\n" +
	"\x0fremaining_limit\x18\x03 \x01(\x02R\x0eremainingLimit2J\n" +
	"\rBudgetService\x129\n" +
	"\fEvaluateItem\x12\x12.proto.ItemRequest\x1a\x15.proto.BudgetResponseB!Z\x1ffinstream/audit/finstream/protob\x06proto3"

var (
	file_audit_proto_rawDescOnce sync.Once
	file_audit_proto_rawDescData []byte
)

func file_audit_proto_rawDescGZIP() []byte {
	file_audit_proto_rawDescOnce.Do(func() {
		file_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)))
	})
	return file_audit_proto_rawDescData
}

var file_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_audit_proto_goTypes = []any{
	(*ItemRequest)(nil),    // 0: proto.ItemRequest
	(*BudgetResponse)(nil), // 1: proto.BudgetResponse
}
var file_audit_proto_depIdxs = []int32{
	0, // 0: proto.BudgetService.EvaluateItem:input_type -> proto.ItemRequest
	1, // 1: proto.BudgetService.EvaluateItem:output_type -> proto.BudgetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_audit_proto_init() }
func file_audit_proto_init() {
	if File_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_proto_goTypes,
		DependencyIndexes: file_audit_proto_depIdxs,
		MessageInfos:      file_audit_proto_msgTypes,
	}.Build()
	File_audit_proto = out.File
	file_audit_proto_goTypes = nil
	file_audit_proto_depIdxs = nil
}
