# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audit.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udit.proto\x12\x05proto\"*\n\x0bItemRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\"O\n\x0e\x42udgetResponse\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x12\n\nsuggestion\x18\x02 \x01(\t\x12\x17\n\x0fremaining_limit\x18\x03 \x01(\x02\x32J\n\rBudgetService\x12\x39\n\x0c\x45valuateItem\x12\x12.proto.ItemRequest\x1a\x15.proto.BudgetResponseB!Z\x1f\x66instream/audit/finstream/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037finstream/audit/finstream/proto'
  _globals['_ITEMREQUEST']._serialized_start=22
  _globals['_ITEMREQUEST']._serialized_end=64
  _globals['_BUDGETRESPONSE']._serialized_start=66
  _globals['_BUDGETRESPONSE']._serialized_end=145
  _globals['_BUDGETSERVICE']._serialized_start=147
  _globals['_BUDGETSERVICE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
